version: '3.8'

services:
  discord-autobump:
    image: ghcr.io/hiizun/disboard-autobump:latest
    container_name: discord-autobump
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"  # Health check port
    volumes:
      - ./logs:/app/logs
    networks:
      - autobump-network
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  autobump-network:
    driver: bridge
