version: '3.8'

services:
  discord-autobump:
    image: ghcr.io/hiizun/disboard-autobump:latest
    # Note: container_name is not supported in Swarm mode
    deploy:
      replicas: 1
    ports:
      - "3000:3000"  # Health check port
    # Use default overlay network for Swarm
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
